services:
  - type: web
    name: fastapi-course-reg
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      prisma generate
      prisma py fetch
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://courseregdb_user:Vx7LL0r5Z2p0tmkViq8r3XNFPLLvVHrv@dpg-d489qbs9c44c73b1cnr0-a/courseregdb
      - key: PORT
        value: "4000"
